import React from 'react';
import './App.css';

const headers = ["Last Name", "First Name", "Position", "Department", "Manager"]
const lastNames = ["Smith", "Johnson", "Williams", "Brown", "Jones"];
const firstNames = ["James", "John", "Robert", "Michael", "William"];
const positions = ["Manager", "Manager", "Engineer", "Engineer", "Intern"];
const departments = ["Front-End", "Back-End", "Front-End", "Back-End", "Back-End"];
const managers = ["NULL", "NULL", "James Smith", "John Johnson", "John Johnson"];

function App() {
  var table = document.createElement("table");
  var rowHead = document.createElement("tr");
  var lastNameHead = document.createElement("th");
  lastNameHead.innerText = headers[0];
  rowHead.appendChild(lastNameHead);
  var firstNameHead = document.createElement("th");
  firstNameHead.innerText = headers[1];
  rowHead.appendChild(firstNameHead);
  var positionHead = document.createElement("th");
  positionHead.innerText = headers[2];
  rowHead.appendChild(positionHead);
  var departmentHead = document.createElement("th");
  departmentHead.innerText = headers[3];
  rowHead.appendChild(departmentHead);
  var managerHead = document.createElement("th");
  managerHead.innerText = headers[4];
  rowHead.appendChild(managerHead);
  table.appendChild(rowHead);
  for(var i = 0; i < lastNames.length; i++) {
    var row = document.createElement("tr");
    var lastName = document.createElement('td');
    lastName.innerText = lastNames[i];
    row.appendChild(lastName);
    var firstName = document.createElement('td');
    firstName.innerText = firstNames[i];
    row.appendChild(firstName);
    var position = document.createElement('td');
    position.innerText = positions[i];
    row.appendChild(position);
    var department = document.createElement('td');
    department.innerText = departments[i];
    row.appendChild(department);
    var manager = document.createElement('td');
    manager.innerText = managers[i];
    row.appendChild(manager);
    table.appendChild(row);
  }
  // var row0 = document.createElement("tr");
  // var lastName0 = document.createElement('td');
  // lastName0.innerText = lastNames[0];
  // row0.appendChild(lastName0);
  // var firstName0 = document.createElement('td');
  // firstName0.innerText = firstNames[0];
  // row0.appendChild(firstName0);
  // var position0 = document.createElement('td');
  // position0.innerText = positions[0];
  // row0.appendChild(position0);
  // var department0 = document.createElement('td');
  // department0.innerText = departments[0];
  // row0.appendChild(department0);
  // var manager0 = document.createElement('td');
  // manager0.innerText = managers[0];
  // row0.appendChild(manager0);
  // table.appendChild(row0);
  // var row1 = document.createElement("tr");
  // var lastName1 = document.createElement('td');
  // lastName1.innerText = lastNames[1];
  // row1.appendChild(lastName1);
  // var firstName1 = document.createElement('td');
  // firstName1.innerText = firstNames[1];
  // row1.appendChild(firstName1);
  // var position1 = document.createElement('td');
  // position1.innerText = positions[1];
  // row1.appendChild(position1);
  // var department1 = document.createElement('td');
  // department1.innerText = departments[1];
  // row1.appendChild(department1);
  // var manager1 = document.createElement('td');
  // manager1.innerText = managers[1];
  // row1.appendChild(manager1);
  // table.appendChild(row1);
  // var row2 = document.createElement("tr");
  // var lastName2 = document.createElement('td');
  // lastName2.innerText = lastNames[2];
  // row2.appendChild(lastName2);
  // var firstName2 = document.createElement('td');
  // firstName2.innerText = firstNames[2];
  // row2.appendChild(firstName2);
  // var position2 = document.createElement('td');
  // position2.innerText = positions[2];
  // row2.appendChild(position2);
  // var department2 = document.createElement('td');
  // department2.innerText = departments[2];
  // row2.appendChild(department2);
  // var manager2 = document.createElement('td');
  // manager2.innerText = managers[2];
  // row2.appendChild(manager2);
  // table.appendChild(row2);
  // var row3 = document.createElement("tr");
  // var lastName3 = document.createElement('td');
  // lastName3.innerText = lastNames[3];
  // row3.appendChild(lastName3);
  // var firstName3 = document.createElement('td');
  // firstName3.innerText = firstNames[3];
  // row3.appendChild(firstName3);
  // var position3 = document.createElement('td');
  // position3.innerText = positions[3];
  // row3.appendChild(position3);
  // var department3 = document.createElement('td');
  // department3.innerText = departments[3];
  // row3.appendChild(department3);
  // var manager3 = document.createElement('td');
  // manager3.innerText = managers[3];
  // row3.appendChild(manager3);
  // table.appendChild(row3);
  // var row4 = document.createElement("tr");
  // var lastName4 = document.createElement('td');
  // lastName4.innerText = lastNames[4];
  // row4.appendChild(lastName4);
  // var firstName4 = document.createElement('td');
  // firstName4.innerText = firstNames[4];
  // row4.appendChild(firstName4);
  // var position4 = document.createElement('td');
  // position4.innerText = positions[4];
  // row4.appendChild(position4);
  // var department4 = document.createElement('td');
  // department4.innerText = departments[4];
  // row4.appendChild(department4);
  // var manager4 = document.createElement('td');
  // manager4.innerText = managers[4];
  // row4.appendChild(manager4);
  // table.appendChild(row4);
  return (
    <div className="App" ref={node => node.appendChild(table)}></div>
  );
}

export default App;
